export class RailSeedData {

    createDb() {
        let railcar = [
                    { id: 1,
            carLoadNumber:"95308656",
            numberInvoice:"40143976",
            dateExtractInvoice:"24.07.2015",
            owner:"GLENCORE GRAIN BV",
            furnisher:"NILSEN LLP",
            sender:"",
            stationSender:"Ст. Заплазы Од. жд.",
            nameCulture:"Ячмень",
             weightBrruttoInvoice:"79300",
            weightTareInvoice:"20750",	
            weightNetInvoice:"",
            gmo:false,
            certificate:"1234",
            certificateDate:"24.07.2015",
            securityProtocol:"1234",
            brruttoTime:"29.07.2015 8:42",
            uncorrespondeseTime:"29.07.2015 10:27",
            tareTime:"29.07.2015 13:21",
            brruttoIZT:"79300",
            netIZT:"",
            tareIZT:"",            
            brruttoDifference:"-550",
            netDifference:"-500",
            meansWeight:"же/д",
            delayReason:"Выяснение по брутто",
            permisionResult:"false",
            permisionTime:"30.07.2015 14:30",
            permisionName:"Г.Шеховцова",
            overTime:"",
            remark:"" },
            { id: 2,
            carLoadNumber:"95308656",
            numberInvoice:"40143976",
            dateExtractInvoice:"24.07.2015",
            owner:"GLENCORE GRAIN BV",
            furnisher:"NILSEN LLP",
            sender:"",
            stationSender:"Ст. Заплазы Од. жд.",
            nameCulture:"Ячмень",
             weightBrruttoInvoice:"79300",
            weightTareInvoice:"20750",	
            weightNetInvoice:"",
            gmo:false,
            certificate:"1234",
            certificateDate:"24.07.2015",
            securityProtocol:"1234",
            brruttoTime:"29.07.2015 8:42",
            uncorrespondeseTime:"29.07.2015 10:27",
            tareTime:"29.07.2015 13:21",
            brruttoIZT:"79300",
            netIZT:"",
            tareIZT:"",            
            brruttoDifference:"-550",
            netDifference:"-500",
            meansWeight:"же/д",
            delayReason:"Выяснение по брутто",
            permisionResult:"false",
            permisionTime:"30.07.2015 14:30",
            permisionName:"Г.Шеховцова",
            overTime:"",
            remark:"" }
        ];

        return { railcar };
    }

}
